import { Router } from "express";
import areasRoutes from "./areas.routes.js";
import cashsessionsRoutes from "./cashsessions.routes.js";
import categoriesRoutes from "./categories.routes.js";
import customersRoutes from "./customers.routes.js";
import ingredientsRoutes from "./ingredients.routes.js";
import modifiersRoutes from "./modifiers.routes.js";
import orderitemmodifiersRoutes from "./orderitemmodifiers.routes.js";
import orderitemsRoutes from "./orderitems.routes.js";
import orderstatushistoryRoutes from "./orderstatushistory.routes.js";
import ordersRoutes from "./orders.routes.js";
import paymentallocationsRoutes from "./paymentallocations.routes.js";
import paymentsRoutes from "./payments.routes.js";
import productmodifiersRoutes from "./productmodifiers.routes.js";
import productpricesRoutes from "./productprices.routes.js";
import productsRoutes from "./products.routes.js";
import purchaseitemsRoutes from "./purchaseitems.routes.js";
import purchaseordersRoutes from "./purchaseorders.routes.js";
import recipeitemsRoutes from "./recipeitems.routes.js";
import recipesRoutes from "./recipes.routes.js";
import reservationtablesRoutes from "./reservationtables.routes.js";
import reservationsRoutes from "./reservations.routes.js";
import restauranttablesRoutes from "./restauranttables.routes.js";
import shiftsRoutes from "./shifts.routes.js";
import stockitemsRoutes from "./stockitems.routes.js";
import stockmovesRoutes from "./stockmoves.routes.js";
import suppliersRoutes from "./suppliers.routes.js";
import usersRoutes from "./users.routes.js";
import warehousesRoutes from "./warehouses.routes.js";

const router = Router();

router.use("/areas", areasRoutes);
router.use("/cashsessions", cashsessionsRoutes);
router.use("/categories", categoriesRoutes);
router.use("/customers", customersRoutes);
router.use("/ingredients", ingredientsRoutes);
router.use("/modifiers", modifiersRoutes);
router.use("/orderitemmodifiers", orderitemmodifiersRoutes);
router.use("/orderitems", orderitemsRoutes);
router.use("/orderstatushistory", orderstatushistoryRoutes);
router.use("/orders", ordersRoutes);
router.use("/paymentallocations", paymentallocationsRoutes);
router.use("/payments", paymentsRoutes);
router.use("/productmodifiers", productmodifiersRoutes);
router.use("/productprices", productpricesRoutes);
router.use("/products", productsRoutes);
router.use("/purchaseitems", purchaseitemsRoutes);
router.use("/purchaseorders", purchaseordersRoutes);
router.use("/recipeitems", recipeitemsRoutes);
router.use("/recipes", recipesRoutes);
router.use("/reservationtables", reservationtablesRoutes);
router.use("/reservations", reservationsRoutes);
router.use("/restauranttables", restauranttablesRoutes);
router.use("/shifts", shiftsRoutes);
router.use("/stockitems", stockitemsRoutes);
router.use("/stockmoves", stockmovesRoutes);
router.use("/suppliers", suppliersRoutes);
router.use("/users", usersRoutes);
router.use("/warehouses", warehousesRoutes);

export default router;